pipeline {
   agent {
      docker {
        image 'node:latest' 
      }
   }

   stages {
      stage ( 'Test' ) {
	 environment {
            CI = 'true'
         }
         steps {
            echo  "Testing"
            sh 'cd front-end && yarn install && yarn test'
         }
      }
      stage ( 'Build' ) {
         steps {
            echo  "Building"
            sh 'cd front-end && yarn install && yarn build'
         }
      }
   }
}
