pipeline {
   agent none

   stages {
      stage ( 'Build' ) {
	 agent {
            docker {
              image 'node:latest' 
            }
         }
         steps {
            echo  "Building"
            sh 'cd front-end && npm install && yarn build'
         }
      }
   }
}
