pipeline {
   agent none

   stages {
      stage ( 'Test' ) {
	 agent {
            docker {
              image 'python:3-alpine' 
            }
         }
         steps {
            echo  "Testing"
            sh  'pip install virtualenv && virtualenv venv && . venv/bin/activate && pip install -r ./cs4500-spring2018-team42-flask/requirements.txt && pip install pytest && python -m pytest ./cs4500-spring2018-team42-flask/tests/* --verbose --junit-xml results.xml'
         }
      }
   }
}
